### ISSUE TITLE
Last Changes from the amends/comments doc

### ISSUE THREAD

**Issue by timmwille** [opencultureagency/Open-Learning-Guide#5]
# jHUB POSTER AMENDS v2

## OPEN LEARNING GUIDE A1 SIDE 1

- [ ] **Title: What is jHUB?**
even though title all caps, still use small j for jHUB
add jHUB Pioneers list? (if it fits) 
I think change video workshop image to one with girl in pink at the camera – sent in email?
- [ ] Add URL for jHUB! (think I forgot this earlier)
http://jubahub.org/

- [ ] Glossary:
*“blended learning” is not yet highlighted and separated in bold as the other terms. 
*add wiki definition

- [ ] Wiki: a website or database developed collaboratively by a community of users, allowing any user to add, edit, revise and delete content.

- [ ] *Add Credits – partner organisations (and people tbc as per separate doc)
Please separate BMZ Logo from others eg 3 Collaborators / Partners  + 1 supporter = BMZ. For the BMZ Logo please use the Version with sub-line "With the financial support from" in Dropbox. 

## OPEN LEARNING GUIDE A1 SIDE 2

- [ ] Open Learning Intro P2P section:
iceHubs Global eLEARNING (only G capitalised)

- [ ] eLEARNING RESOURCES
*add (if it doesn't fit – replace the MOOC entry – think this is more fun and useful!)
Crash Course
https://www.youtube.com/user/crashcourse/playlists
Youtube channel with courses in Anatomy & Physiology, Astronomy, World History, Biology, Literature, Ecology, Economics, Chemistry, Psychology in short episodes.

- [ ] DIGITAL CREATION AND STORY-TELLING PLATFORMS 
Add “MEDIA” (overall basis of project – forgot to include it in the text so trying to find places to add..) eg: Digital Media Creation and Story-telling Platforms

- [ ] ANIMATION, 3D MODELLING, SOUND & VIDEO EDITING
Pls remove '3D Studio Max" from title – if fits, start with 'MEDIA TOOLS:' but if not, is ok.

- [ ] *Add to CODING AND PROGRAMMING

- [ ] OPEN CULTURE LEARN TO CODE
DIY Guide: learn how to code for free, using online courses, instructional videos, YouTube channels, textbooks.
http://www.openculture.com/2016/03/learn-how-to-code-for-free-a-diy-guide-for-learning-html-python-javascript-more.html

**Comment by timmwille** [comment]
perfect @Glock1967 if you check if these are already in the first print edition, mark them

**Comment by Glock1967** [comment]
Small j is used for jHUB in both editions of the poster

Jubahub.org link is on both editions of the poster

*“blended learning” is highlighted and separated in bold as the other terms in both editions of the poster

There is a wiki definition on both editions of the poster

Both editions of the poster state they are funded by the BMZ

iceHubs Global eLEARNING  same on both editions of the poster

Crash course is on both poster editions

"Digital media creation and storytelling platforms" is present in both editions

OPEN CULTURE LEARN TO CODE is present in both posters

**Comment by timmwille** [comment]
ok cool so we can close this
